service: todo

plugins:
  - serverless-webpack
  - serverless-domain-manager

custom:
  customDomain:
    domainName: todo.medgelabs.io
    certificateName: 'todo'
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  stage: dev

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: /
          integration: lambda-proxy
